name = "BioinfoTools"
uuid = "00eaa582-b862-4e15-ad52-40bcea7257db"
authors = ["thomaswolfe <thomas_wolfe@student.uml.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
