name = "BioinfoTools"
uuid = "00eaa582-b862-4e15-ad52-40bcea7257db"
version = "0.1.0"
authors = ["thomaswolfe <thomas_wolfe@student.uml.edu> and contributors"]

[deps]
BED = "8e4a8c10-cb6b-11e8-08d2-83478d609d67"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
GFF3 = "af1dc308-cb6b-11e8-32f0-31192efa90f6"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
NaturalSort = "c020b1a1-e9b0-503a-9c33-f039bfc54a85"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
XAM = "d759349c-bcba-11e9-07c2-5b90f8f05f7c"
YeoJohnsonTrans = "bde5d4e9-ba51-5a47-b2d1-b5088a182367"

[compat]
BED = "0.3.1"
BioSequences = "3.5.0"
CSV = "0.10.15"
CodecZlib = "0.7.8"
DataFrames = "1.8.1"
GFF3 = "0.2.3"
GenomicFeatures = "2.1.0"
InteractiveUtils = "1.11.0"
StatsBase = "0.34.6"
XAM = "0.4.2"
YeoJohnsonTrans = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
